---
- name: Installing nginx
  hosts: web01
  become: yes
  
  tasks: 
  - name: install nginx    
    apt:
     name: nginx
     state: present
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: yes
  - name : install git
    apt:
      name: git
      state: present
   
